### ISSUE TITLE
Compiling Error on Ubuntu Server 12.04 x64

### ISSUE THREAD

**Issue by ghost** [grumpycoinc/grumpycoin#1]
/grumpycoin/src$ make -f makefile.unix
/bin/sh ../share/genbuild.sh obj/build.h
/bin/sh: 0: Can't open ../share/genbuild.sh
make: **\* [obj/build.h] Error 127

**Comment by grumpycoinc** [comment]
Thanks for your support. Work in progress for Linux. Please use old commit meanwhile.
